export const countryFlagMap: Record<string, string> = {
  UK: '🇬🇧',
  Ireland: '🇮🇪',
  USA: '🇺🇸',
  Canada: '🇨🇦',
  Germany: '🇩🇪',
  Spain: '🇪🇸',
  Holland: '🇳🇱',
  Switzerland: '🇨🇭',
  Hungary: '🇭🇺',
  Austria: '🇦🇹',
  'Czech Republic': '🇨🇿',
  Poland: '🇵🇱',
  Denmark: '🇩🇰',
  Finland: '🇫🇮',
  India: '🇮🇳',
  Israel: '🇮🇱',
};
